### ISSUE TITLE
Cannot run blog.sh (after macOS High Sierra): Unknown tag 'seo'

### ISSUE THREAD

**Issue by clacote** [Ninja-Squad/ninja-squad.github.com#239]
➜  blog git:(post/ng-5) bundle install
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using addressable 2.4.0
Using bundler 1.15.3
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Using ffi 1.9.10
Using multipart-post 2.0.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.3
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.10.0
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.10.1
Using safe_yaml 1.0.4
Using jekyll-feed 0.5.1
Using mini_portile2 2.0.0
Using jekyll-paginate 1.1.0
Using jekyll-sitemap 0.10.0
Using terminal-table 1.5.2
Using tzinfo 1.2.2
Using coffee-script 2.4.1
Using ethon 0.9.0
Using rb-inotify 0.9.7
Using faraday 0.9.2
Using jekyll-sass-converter 1.3.0
Using nokogiri 1.6.7.2
Using activesupport 4.2.6
Using jekyll-coffeescript 1.0.1
Using typhoeus 0.8.0
Using listen 3.0.6
Using sawyer 0.7.0
Using html-pipeline 2.4.1
Using jekyll-watch 1.4.0
Using octokit 4.3.0
Using jekyll 3.1.6
Using github-pages-health-check 1.1.0
Using jekyll-gist 1.4.0
Using jekyll-github-metadata 1.11.1
Using jekyll-mentions 1.1.2
Using jekyll-redirect-from 0.10.0
Using jekyll-seo-tag 1.4.0
Using jemoji 0.6.2
Using github-pages 80
Bundle complete! 2 Gemfile dependencies, 50 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
➜  blog git:(post/ng-5) ./blog.sh 
Configuration file: /Users/sryl/workspace/ninja/blog/_config.yml
       Deprecation: The 'plugins' configurationoption has been renamed to 'plugins_dir'. Please update your config file accordingly.
            Source: /Users/sryl/workspace/ninja/blog
       Destination: /Users/sryl/workspace/ninja/blog/_site
 Incremental build: enabled
      Generating... 
  Liquid Exception: Liquid syntax error (line 37): Unknown tag 'seo' in _includes/themes/twitter/default.html, included in _layouts/default.html
jekyll 3.1.6 | Error:  Liquid syntax error (line 37): Unknown tag 'seo'
➜  blog git:(post/ng-5)

**Comment by jnizet** [comment]
Same here on the post/ng-5 branch, but it works fine on master. Very strange.

**Comment by jnizet** [comment]
I take that back. After switching back and forth between branches and resetting to master, it doesn't build on master anymore.

Removing this seo tag makes the generation pass again, but removes pretty important stuff from the head:
```
<!-- Begin Jekyll SEO tag v2.3.0 -->
<title>Le Blog | Ninja Squad</title>
<meta property="og:title" content="Le Blog" />
<meta name="author" content="Ninja Squad" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="NinjaSquad’s Awesome Blog" />
<meta property="og:description" content="NinjaSquad’s Awesome Blog" />
<link rel="canonical" href="http://blog.ninja-squad.com/" />
<meta property="og:url" content="http://blog.ninja-squad.com/" />
<meta property="og:site_name" content="Ninja Squad" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@NinjaSquad" />
<meta name="twitter:creator" content="@NinjaSquad" />
<meta property="article:publisher" content="ninjasquadfr" />
<script type="application/ld+json">
{"name":"Ninja Squad","description":"NinjaSquad’s Awesome Blog","author":{"@type":"Person","name":"Ninja Squad"},"@type":"WebSite","url":"http://blog.ninja-squad.com/","image":null,"publisher":{"@type":"Organization","logo":{"@type":"ImageObject","url":"http://blog.ninja-squad.com/assets/images/logo-flat-600.png"},"name":"Ninja Squad"},"headline":"Le Blog","dateModified":null,"datePublished":null,"sameAs":null,"mainEntityOfPage":null,"@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->
```

**Comment by clacote** [comment]
That might be because of this: https://github.com/Ninja-Squad/ninja-squad.github.com/commit/5b23980d4e4cadcb4c0d2fe42bc012c13f1a1556#diff-aeb42283af8ef8e9da40ededd3ae2ab2L48

**Comment by jnizet** [comment]
I just used `bundle update`, and everything went fine after that.

**Comment by clacote** [comment]
👍, `bundle update` fixed this issue!
